// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1i6UTb7_CQ_YW2L5_22HPX8fZIZJ-zlc',
    appId: '1:727606836878:web:f8b9f43d56e6267c2593df',
    messagingSenderId: '727606836878',
    projectId: 'codeathon2',
    authDomain: 'codeathon2.firebaseapp.com',
    storageBucket: 'codeathon2.firebasestorage.app',
    measurementId: 'G-9R6H3880WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbYZHEwDLF6S4JKXVPBrGPFsdIF04zWtw',
    appId: '1:727606836878:android:ad1343a6165091082593df',
    messagingSenderId: '727606836878',
    projectId: 'codeathon2',
    storageBucket: 'codeathon2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu6FmNA3JK7pWh2oOkGmAgLUFJn2ko9O8',
    appId: '1:727606836878:ios:d141aa4cba536ada2593df',
    messagingSenderId: '727606836878',
    projectId: 'codeathon2',
    storageBucket: 'codeathon2.firebasestorage.app',
    iosBundleId: 'com.example.codeathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu6FmNA3JK7pWh2oOkGmAgLUFJn2ko9O8',
    appId: '1:727606836878:ios:d141aa4cba536ada2593df',
    messagingSenderId: '727606836878',
    projectId: 'codeathon2',
    storageBucket: 'codeathon2.firebasestorage.app',
    iosBundleId: 'com.example.codeathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1i6UTb7_CQ_YW2L5_22HPX8fZIZJ-zlc',
    appId: '1:727606836878:web:1c933c5e71edc60a2593df',
    messagingSenderId: '727606836878',
    projectId: 'codeathon2',
    authDomain: 'codeathon2.firebaseapp.com',
    storageBucket: 'codeathon2.firebasestorage.app',
    measurementId: 'G-ZM11EW0JRE',
  );
}
